name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build
      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: packages/*/dist

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: packages
      - run: yarn typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - name: Build tree-sitter native bindings
        run: npx --yes node-gyp rebuild
        working-directory: node_modules/tree-sitter
      - run: yarn test
